/// Flutter icons IconsEM
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconsEM
///      fonts:
///       - asset: fonts/IconsEM.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconsEM {
  IconsEM._();

  static const _kFontFam = 'IconsEM';
  static const String? _kFontPkg = null;

  static const IconData plane = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData planeflies = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData locationpin = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bed = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnifyingglass = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData planedepart = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upanddown = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
